// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GlobalRespProto.proto

package com.funcy.g01.base.proto.bo;

public final class GlobalRespProtoBuffer {
  private GlobalRespProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RoleInfoVoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 id = 1;
    /**
     * <code>optional int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    // optional string platformId = 2;
    /**
     * <code>optional string platformId = 2;</code>
     */
    boolean hasPlatformId();
    /**
     * <code>optional string platformId = 2;</code>
     */
    java.lang.String getPlatformId();
    /**
     * <code>optional string platformId = 2;</code>
     */
    com.google.protobuf.ByteString
        getPlatformIdBytes();

    // optional string roleName = 3;
    /**
     * <code>optional string roleName = 3;</code>
     */
    boolean hasRoleName();
    /**
     * <code>optional string roleName = 3;</code>
     */
    java.lang.String getRoleName();
    /**
     * <code>optional string roleName = 3;</code>
     */
    com.google.protobuf.ByteString
        getRoleNameBytes();

    // optional int32 roleLevel = 4;
    /**
     * <code>optional int32 roleLevel = 4;</code>
     */
    boolean hasRoleLevel();
    /**
     * <code>optional int32 roleLevel = 4;</code>
     */
    int getRoleLevel();

    // optional int32 vipLevel = 5;
    /**
     * <code>optional int32 vipLevel = 5;</code>
     */
    boolean hasVipLevel();
    /**
     * <code>optional int32 vipLevel = 5;</code>
     */
    int getVipLevel();

    // optional int32 photo = 6;
    /**
     * <code>optional int32 photo = 6;</code>
     */
    boolean hasPhoto();
    /**
     * <code>optional int32 photo = 6;</code>
     */
    int getPhoto();

    // optional int32 lastSyncAt = 7;
    /**
     * <code>optional int32 lastSyncAt = 7;</code>
     */
    boolean hasLastSyncAt();
    /**
     * <code>optional int32 lastSyncAt = 7;</code>
     */
    int getLastSyncAt();

    // optional int64 loginTime = 8;
    /**
     * <code>optional int64 loginTime = 8;</code>
     */
    boolean hasLoginTime();
    /**
     * <code>optional int64 loginTime = 8;</code>
     */
    long getLoginTime();

    // optional int64 createTime = 9;
    /**
     * <code>optional int64 createTime = 9;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>optional int64 createTime = 9;</code>
     */
    long getCreateTime();

    // optional string regIp = 10;
    /**
     * <code>optional string regIp = 10;</code>
     */
    boolean hasRegIp();
    /**
     * <code>optional string regIp = 10;</code>
     */
    java.lang.String getRegIp();
    /**
     * <code>optional string regIp = 10;</code>
     */
    com.google.protobuf.ByteString
        getRegIpBytes();

    // optional string loginIp = 11;
    /**
     * <code>optional string loginIp = 11;</code>
     */
    boolean hasLoginIp();
    /**
     * <code>optional string loginIp = 11;</code>
     */
    java.lang.String getLoginIp();
    /**
     * <code>optional string loginIp = 11;</code>
     */
    com.google.protobuf.ByteString
        getLoginIpBytes();

    // optional string token = 12;
    /**
     * <code>optional string token = 12;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 12;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 12;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // optional int32 areaId = 13;
    /**
     * <code>optional int32 areaId = 13;</code>
     */
    boolean hasAreaId();
    /**
     * <code>optional int32 areaId = 13;</code>
     */
    int getAreaId();
  }
  /**
   * Protobuf type {@code proto.RoleInfoVo}
   */
  public static final class RoleInfoVo extends
      com.google.protobuf.GeneratedMessage
      implements RoleInfoVoOrBuilder {
    // Use RoleInfoVo.newBuilder() to construct.
    private RoleInfoVo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoleInfoVo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoleInfoVo defaultInstance;
    public static RoleInfoVo getDefaultInstance() {
      return defaultInstance;
    }

    public RoleInfoVo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoleInfoVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              platformId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              roleName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              roleLevel_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              vipLevel_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              photo_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              lastSyncAt_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              loginTime_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              createTime_ = input.readInt64();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              regIp_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              loginIp_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              token_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              areaId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.internal_static_proto_RoleInfoVo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.internal_static_proto_RoleInfoVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.class, com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.Builder.class);
    }

    public static com.google.protobuf.Parser<RoleInfoVo> PARSER =
        new com.google.protobuf.AbstractParser<RoleInfoVo>() {
      public RoleInfoVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleInfoVo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoleInfoVo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional string platformId = 2;
    public static final int PLATFORMID_FIELD_NUMBER = 2;
    private java.lang.Object platformId_;
    /**
     * <code>optional string platformId = 2;</code>
     */
    public boolean hasPlatformId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string platformId = 2;</code>
     */
    public java.lang.String getPlatformId() {
      java.lang.Object ref = platformId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platformId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string platformId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformIdBytes() {
      java.lang.Object ref = platformId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platformId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string roleName = 3;
    public static final int ROLENAME_FIELD_NUMBER = 3;
    private java.lang.Object roleName_;
    /**
     * <code>optional string roleName = 3;</code>
     */
    public boolean hasRoleName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string roleName = 3;</code>
     */
    public java.lang.String getRoleName() {
      java.lang.Object ref = roleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roleName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string roleName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 roleLevel = 4;
    public static final int ROLELEVEL_FIELD_NUMBER = 4;
    private int roleLevel_;
    /**
     * <code>optional int32 roleLevel = 4;</code>
     */
    public boolean hasRoleLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 roleLevel = 4;</code>
     */
    public int getRoleLevel() {
      return roleLevel_;
    }

    // optional int32 vipLevel = 5;
    public static final int VIPLEVEL_FIELD_NUMBER = 5;
    private int vipLevel_;
    /**
     * <code>optional int32 vipLevel = 5;</code>
     */
    public boolean hasVipLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 vipLevel = 5;</code>
     */
    public int getVipLevel() {
      return vipLevel_;
    }

    // optional int32 photo = 6;
    public static final int PHOTO_FIELD_NUMBER = 6;
    private int photo_;
    /**
     * <code>optional int32 photo = 6;</code>
     */
    public boolean hasPhoto() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 photo = 6;</code>
     */
    public int getPhoto() {
      return photo_;
    }

    // optional int32 lastSyncAt = 7;
    public static final int LASTSYNCAT_FIELD_NUMBER = 7;
    private int lastSyncAt_;
    /**
     * <code>optional int32 lastSyncAt = 7;</code>
     */
    public boolean hasLastSyncAt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 lastSyncAt = 7;</code>
     */
    public int getLastSyncAt() {
      return lastSyncAt_;
    }

    // optional int64 loginTime = 8;
    public static final int LOGINTIME_FIELD_NUMBER = 8;
    private long loginTime_;
    /**
     * <code>optional int64 loginTime = 8;</code>
     */
    public boolean hasLoginTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 loginTime = 8;</code>
     */
    public long getLoginTime() {
      return loginTime_;
    }

    // optional int64 createTime = 9;
    public static final int CREATETIME_FIELD_NUMBER = 9;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 9;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 createTime = 9;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    // optional string regIp = 10;
    public static final int REGIP_FIELD_NUMBER = 10;
    private java.lang.Object regIp_;
    /**
     * <code>optional string regIp = 10;</code>
     */
    public boolean hasRegIp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string regIp = 10;</code>
     */
    public java.lang.String getRegIp() {
      java.lang.Object ref = regIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          regIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string regIp = 10;</code>
     */
    public com.google.protobuf.ByteString
        getRegIpBytes() {
      java.lang.Object ref = regIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string loginIp = 11;
    public static final int LOGINIP_FIELD_NUMBER = 11;
    private java.lang.Object loginIp_;
    /**
     * <code>optional string loginIp = 11;</code>
     */
    public boolean hasLoginIp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string loginIp = 11;</code>
     */
    public java.lang.String getLoginIp() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string loginIp = 11;</code>
     */
    public com.google.protobuf.ByteString
        getLoginIpBytes() {
      java.lang.Object ref = loginIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string token = 12;
    public static final int TOKEN_FIELD_NUMBER = 12;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 12;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string token = 12;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 areaId = 13;
    public static final int AREAID_FIELD_NUMBER = 13;
    private int areaId_;
    /**
     * <code>optional int32 areaId = 13;</code>
     */
    public boolean hasAreaId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 areaId = 13;</code>
     */
    public int getAreaId() {
      return areaId_;
    }

    private void initFields() {
      id_ = 0L;
      platformId_ = "";
      roleName_ = "";
      roleLevel_ = 0;
      vipLevel_ = 0;
      photo_ = 0;
      lastSyncAt_ = 0;
      loginTime_ = 0L;
      createTime_ = 0L;
      regIp_ = "";
      loginIp_ = "";
      token_ = "";
      areaId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPlatformIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, roleLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, vipLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, photo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, lastSyncAt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, loginTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, createTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getRegIpBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getLoginIpBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getTokenBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, areaId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPlatformIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, roleLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, vipLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, photo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, lastSyncAt_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, loginTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, createTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getRegIpBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getLoginIpBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getTokenBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, areaId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RoleInfoVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.internal_static_proto_RoleInfoVo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.internal_static_proto_RoleInfoVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.class, com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        platformId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        roleLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        vipLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        photo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        lastSyncAt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        loginTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        regIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        loginIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        areaId_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.internal_static_proto_RoleInfoVo_descriptor;
      }

      public com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo build() {
        com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo buildPartial() {
        com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo result = new com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.platformId_ = platformId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roleName_ = roleName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roleLevel_ = roleLevel_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.vipLevel_ = vipLevel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.photo_ = photo_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.lastSyncAt_ = lastSyncAt_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.loginTime_ = loginTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.regIp_ = regIp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.loginIp_ = loginIp_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.areaId_ = areaId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo) {
          return mergeFrom((com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo other) {
        if (other == com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPlatformId()) {
          bitField0_ |= 0x00000002;
          platformId_ = other.platformId_;
          onChanged();
        }
        if (other.hasRoleName()) {
          bitField0_ |= 0x00000004;
          roleName_ = other.roleName_;
          onChanged();
        }
        if (other.hasRoleLevel()) {
          setRoleLevel(other.getRoleLevel());
        }
        if (other.hasVipLevel()) {
          setVipLevel(other.getVipLevel());
        }
        if (other.hasPhoto()) {
          setPhoto(other.getPhoto());
        }
        if (other.hasLastSyncAt()) {
          setLastSyncAt(other.getLastSyncAt());
        }
        if (other.hasLoginTime()) {
          setLoginTime(other.getLoginTime());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasRegIp()) {
          bitField0_ |= 0x00000200;
          regIp_ = other.regIp_;
          onChanged();
        }
        if (other.hasLoginIp()) {
          bitField0_ |= 0x00000400;
          loginIp_ = other.loginIp_;
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000800;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasAreaId()) {
          setAreaId(other.getAreaId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.GlobalRespProtoBuffer.RoleInfoVo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 id = 1;
      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional string platformId = 2;
      private java.lang.Object platformId_ = "";
      /**
       * <code>optional string platformId = 2;</code>
       */
      public boolean hasPlatformId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string platformId = 2;</code>
       */
      public java.lang.String getPlatformId() {
        java.lang.Object ref = platformId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          platformId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string platformId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformIdBytes() {
        java.lang.Object ref = platformId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platformId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string platformId = 2;</code>
       */
      public Builder setPlatformId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        platformId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string platformId = 2;</code>
       */
      public Builder clearPlatformId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        platformId_ = getDefaultInstance().getPlatformId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string platformId = 2;</code>
       */
      public Builder setPlatformIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        platformId_ = value;
        onChanged();
        return this;
      }

      // optional string roleName = 3;
      private java.lang.Object roleName_ = "";
      /**
       * <code>optional string roleName = 3;</code>
       */
      public boolean hasRoleName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string roleName = 3;</code>
       */
      public java.lang.String getRoleName() {
        java.lang.Object ref = roleName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          roleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string roleName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRoleNameBytes() {
        java.lang.Object ref = roleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string roleName = 3;</code>
       */
      public Builder setRoleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        roleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string roleName = 3;</code>
       */
      public Builder clearRoleName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleName_ = getDefaultInstance().getRoleName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string roleName = 3;</code>
       */
      public Builder setRoleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        roleName_ = value;
        onChanged();
        return this;
      }

      // optional int32 roleLevel = 4;
      private int roleLevel_ ;
      /**
       * <code>optional int32 roleLevel = 4;</code>
       */
      public boolean hasRoleLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 roleLevel = 4;</code>
       */
      public int getRoleLevel() {
        return roleLevel_;
      }
      /**
       * <code>optional int32 roleLevel = 4;</code>
       */
      public Builder setRoleLevel(int value) {
        bitField0_ |= 0x00000008;
        roleLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roleLevel = 4;</code>
       */
      public Builder clearRoleLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roleLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 vipLevel = 5;
      private int vipLevel_ ;
      /**
       * <code>optional int32 vipLevel = 5;</code>
       */
      public boolean hasVipLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 vipLevel = 5;</code>
       */
      public int getVipLevel() {
        return vipLevel_;
      }
      /**
       * <code>optional int32 vipLevel = 5;</code>
       */
      public Builder setVipLevel(int value) {
        bitField0_ |= 0x00000010;
        vipLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vipLevel = 5;</code>
       */
      public Builder clearVipLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        vipLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 photo = 6;
      private int photo_ ;
      /**
       * <code>optional int32 photo = 6;</code>
       */
      public boolean hasPhoto() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 photo = 6;</code>
       */
      public int getPhoto() {
        return photo_;
      }
      /**
       * <code>optional int32 photo = 6;</code>
       */
      public Builder setPhoto(int value) {
        bitField0_ |= 0x00000020;
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 photo = 6;</code>
       */
      public Builder clearPhoto() {
        bitField0_ = (bitField0_ & ~0x00000020);
        photo_ = 0;
        onChanged();
        return this;
      }

      // optional int32 lastSyncAt = 7;
      private int lastSyncAt_ ;
      /**
       * <code>optional int32 lastSyncAt = 7;</code>
       */
      public boolean hasLastSyncAt() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 lastSyncAt = 7;</code>
       */
      public int getLastSyncAt() {
        return lastSyncAt_;
      }
      /**
       * <code>optional int32 lastSyncAt = 7;</code>
       */
      public Builder setLastSyncAt(int value) {
        bitField0_ |= 0x00000040;
        lastSyncAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastSyncAt = 7;</code>
       */
      public Builder clearLastSyncAt() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lastSyncAt_ = 0;
        onChanged();
        return this;
      }

      // optional int64 loginTime = 8;
      private long loginTime_ ;
      /**
       * <code>optional int64 loginTime = 8;</code>
       */
      public boolean hasLoginTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 loginTime = 8;</code>
       */
      public long getLoginTime() {
        return loginTime_;
      }
      /**
       * <code>optional int64 loginTime = 8;</code>
       */
      public Builder setLoginTime(long value) {
        bitField0_ |= 0x00000080;
        loginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 loginTime = 8;</code>
       */
      public Builder clearLoginTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        loginTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 createTime = 9;
      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 9;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 createTime = 9;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 9;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000100;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 9;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // optional string regIp = 10;
      private java.lang.Object regIp_ = "";
      /**
       * <code>optional string regIp = 10;</code>
       */
      public boolean hasRegIp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string regIp = 10;</code>
       */
      public java.lang.String getRegIp() {
        java.lang.Object ref = regIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          regIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string regIp = 10;</code>
       */
      public com.google.protobuf.ByteString
          getRegIpBytes() {
        java.lang.Object ref = regIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string regIp = 10;</code>
       */
      public Builder setRegIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        regIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string regIp = 10;</code>
       */
      public Builder clearRegIp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        regIp_ = getDefaultInstance().getRegIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string regIp = 10;</code>
       */
      public Builder setRegIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        regIp_ = value;
        onChanged();
        return this;
      }

      // optional string loginIp = 11;
      private java.lang.Object loginIp_ = "";
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public boolean hasLoginIp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public java.lang.String getLoginIp() {
        java.lang.Object ref = loginIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loginIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public com.google.protobuf.ByteString
          getLoginIpBytes() {
        java.lang.Object ref = loginIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public Builder setLoginIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        loginIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public Builder clearLoginIp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        loginIp_ = getDefaultInstance().getLoginIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string loginIp = 11;</code>
       */
      public Builder setLoginIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        loginIp_ = value;
        onChanged();
        return this;
      }

      // optional string token = 12;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 12;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string token = 12;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 12;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 12;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000800);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 12;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        token_ = value;
        onChanged();
        return this;
      }

      // optional int32 areaId = 13;
      private int areaId_ ;
      /**
       * <code>optional int32 areaId = 13;</code>
       */
      public boolean hasAreaId() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 areaId = 13;</code>
       */
      public int getAreaId() {
        return areaId_;
      }
      /**
       * <code>optional int32 areaId = 13;</code>
       */
      public Builder setAreaId(int value) {
        bitField0_ |= 0x00001000;
        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 areaId = 13;</code>
       */
      public Builder clearAreaId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        areaId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.RoleInfoVo)
    }

    static {
      defaultInstance = new RoleInfoVo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.RoleInfoVo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RoleInfoVo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RoleInfoVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GlobalRespProto.proto\022\005proto\"\354\001\n\nRoleI" +
      "nfoVo\022\n\n\002id\030\001 \001(\003\022\022\n\nplatformId\030\002 \001(\t\022\020\n" +
      "\010roleName\030\003 \001(\t\022\021\n\troleLevel\030\004 \001(\005\022\020\n\010vi" +
      "pLevel\030\005 \001(\005\022\r\n\005photo\030\006 \001(\005\022\022\n\nlastSyncA" +
      "t\030\007 \001(\005\022\021\n\tloginTime\030\010 \001(\003\022\022\n\ncreateTime" +
      "\030\t \001(\003\022\r\n\005regIp\030\n \001(\t\022\017\n\007loginIp\030\013 \001(\t\022\r" +
      "\n\005token\030\014 \001(\t\022\016\n\006areaId\030\r \001(\005B4\n\033com.fun" +
      "cy.g01.base.proto.boB\025GlobalRespProtoBuf" +
      "fer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_RoleInfoVo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_RoleInfoVo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_RoleInfoVo_descriptor,
              new java.lang.String[] { "Id", "PlatformId", "RoleName", "RoleLevel", "VipLevel", "Photo", "LastSyncAt", "LoginTime", "CreateTime", "RegIp", "LoginIp", "Token", "AreaId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
