// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/HallServiceRespProto.proto

package com.funcy.g01.base.proto.service;

public final class HallServiceRespProtoBuffer {
  private HallServiceRespProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HallGetFightRoomInfoRespProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .proto.ServerInfoVo4FrontProto serverInfo = 1;
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    boolean hasServerInfo();
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto getServerInfo();
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder getServerInfoOrBuilder();

    // optional int64 roomId = 2;
    /**
     * <code>optional int64 roomId = 2;</code>
     */
    boolean hasRoomId();
    /**
     * <code>optional int64 roomId = 2;</code>
     */
    long getRoomId();
  }
  /**
   * Protobuf type {@code proto.HallGetFightRoomInfoRespProto}
   */
  public static final class HallGetFightRoomInfoRespProto extends
      com.google.protobuf.GeneratedMessage
      implements HallGetFightRoomInfoRespProtoOrBuilder {
    // Use HallGetFightRoomInfoRespProto.newBuilder() to construct.
    private HallGetFightRoomInfoRespProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HallGetFightRoomInfoRespProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HallGetFightRoomInfoRespProto defaultInstance;
    public static HallGetFightRoomInfoRespProto getDefaultInstance() {
      return defaultInstance;
    }

    public HallGetFightRoomInfoRespProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HallGetFightRoomInfoRespProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = serverInfo_.toBuilder();
              }
              serverInfo_ = input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverInfo_);
                serverInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.internal_static_proto_HallGetFightRoomInfoRespProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.internal_static_proto_HallGetFightRoomInfoRespProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.class, com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.Builder.class);
    }

    public static com.google.protobuf.Parser<HallGetFightRoomInfoRespProto> PARSER =
        new com.google.protobuf.AbstractParser<HallGetFightRoomInfoRespProto>() {
      public HallGetFightRoomInfoRespProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HallGetFightRoomInfoRespProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HallGetFightRoomInfoRespProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .proto.ServerInfoVo4FrontProto serverInfo = 1;
    public static final int SERVERINFO_FIELD_NUMBER = 1;
    private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto serverInfo_;
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    public boolean hasServerInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto getServerInfo() {
      return serverInfo_;
    }
    /**
     * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder getServerInfoOrBuilder() {
      return serverInfo_;
    }

    // optional int64 roomId = 2;
    public static final int ROOMID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>optional int64 roomId = 2;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 roomId = 2;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    private void initFields() {
      serverInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.getDefaultInstance();
      roomId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, serverInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, roomId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, serverInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, roomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.HallGetFightRoomInfoRespProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.internal_static_proto_HallGetFightRoomInfoRespProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.internal_static_proto_HallGetFightRoomInfoRespProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.class, com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getServerInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (serverInfoBuilder_ == null) {
          serverInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.getDefaultInstance();
        } else {
          serverInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.internal_static_proto_HallGetFightRoomInfoRespProto_descriptor;
      }

      public com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto build() {
        com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto buildPartial() {
        com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto result = new com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (serverInfoBuilder_ == null) {
          result.serverInfo_ = serverInfo_;
        } else {
          result.serverInfo_ = serverInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto) {
          return mergeFrom((com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto other) {
        if (other == com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto.getDefaultInstance()) return this;
        if (other.hasServerInfo()) {
          mergeServerInfo(other.getServerInfo());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.service.HallServiceRespProtoBuffer.HallGetFightRoomInfoRespProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .proto.ServerInfoVo4FrontProto serverInfo = 1;
      private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto serverInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder> serverInfoBuilder_;
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public boolean hasServerInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto getServerInfo() {
        if (serverInfoBuilder_ == null) {
          return serverInfo_;
        } else {
          return serverInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public Builder setServerInfo(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto value) {
        if (serverInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverInfo_ = value;
          onChanged();
        } else {
          serverInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public Builder setServerInfo(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder builderForValue) {
        if (serverInfoBuilder_ == null) {
          serverInfo_ = builderForValue.build();
          onChanged();
        } else {
          serverInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public Builder mergeServerInfo(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto value) {
        if (serverInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              serverInfo_ != com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.getDefaultInstance()) {
            serverInfo_ =
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.newBuilder(serverInfo_).mergeFrom(value).buildPartial();
          } else {
            serverInfo_ = value;
          }
          onChanged();
        } else {
          serverInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public Builder clearServerInfo() {
        if (serverInfoBuilder_ == null) {
          serverInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.getDefaultInstance();
          onChanged();
        } else {
          serverInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder getServerInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getServerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder getServerInfoOrBuilder() {
        if (serverInfoBuilder_ != null) {
          return serverInfoBuilder_.getMessageOrBuilder();
        } else {
          return serverInfo_;
        }
      }
      /**
       * <code>optional .proto.ServerInfoVo4FrontProto serverInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder> 
          getServerInfoFieldBuilder() {
        if (serverInfoBuilder_ == null) {
          serverInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.ServerInfoVo4FrontProtoOrBuilder>(
                  serverInfo_,
                  getParentForChildren(),
                  isClean());
          serverInfo_ = null;
        }
        return serverInfoBuilder_;
      }

      // optional int64 roomId = 2;
      private long roomId_ ;
      /**
       * <code>optional int64 roomId = 2;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 roomId = 2;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional int64 roomId = 2;</code>
       */
      public Builder setRoomId(long value) {
        bitField0_ |= 0x00000002;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 roomId = 2;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.HallGetFightRoomInfoRespProto)
    }

    static {
      defaultInstance = new HallGetFightRoomInfoRespProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.HallGetFightRoomInfoRespProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HallGetFightRoomInfoRespProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_HallGetFightRoomInfoRespProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n proto/HallServiceRespProto.proto\022\005prot" +
      "o\032\031proto/GlobalBoProto.proto\032\033proto/SynF" +
      "ightBoProto.proto\"c\n\035HallGetFightRoomInf" +
      "oRespProto\0222\n\nserverInfo\030\001 \001(\0132\036.proto.S" +
      "erverInfoVo4FrontProto\022\016\n\006roomId\030\002 \001(\003B>" +
      "\n com.funcy.g01.base.proto.serviceB\032Hall" +
      "ServiceRespProtoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_HallGetFightRoomInfoRespProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_HallGetFightRoomInfoRespProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_HallGetFightRoomInfoRespProto_descriptor,
              new java.lang.String[] { "ServerInfo", "RoomId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.getDescriptor(),
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
