// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/RankingRespCmdProto.proto

package com.funcy.g01.base.proto.ranking;

public final class RankingRespCmdProtoBuffer {
  private RankingRespCmdProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BytesRespProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes byteArray = 1;
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getByteArrayList();
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    int getByteArrayCount();
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    com.google.protobuf.ByteString getByteArray(int index);
  }
  /**
   * Protobuf type {@code proto.BytesRespProto}
   */
  public static final class BytesRespProto extends
      com.google.protobuf.GeneratedMessage
      implements BytesRespProtoOrBuilder {
    // Use BytesRespProto.newBuilder() to construct.
    private BytesRespProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BytesRespProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BytesRespProto defaultInstance;
    public static BytesRespProto getDefaultInstance() {
      return defaultInstance;
    }

    public BytesRespProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BytesRespProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                byteArray_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              byteArray_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          byteArray_ = java.util.Collections.unmodifiableList(byteArray_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_BytesRespProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_BytesRespProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.class, com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.Builder.class);
    }

    public static com.google.protobuf.Parser<BytesRespProto> PARSER =
        new com.google.protobuf.AbstractParser<BytesRespProto>() {
      public BytesRespProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BytesRespProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BytesRespProto> getParserForType() {
      return PARSER;
    }

    // repeated bytes byteArray = 1;
    public static final int BYTEARRAY_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> byteArray_;
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getByteArrayList() {
      return byteArray_;
    }
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    public int getByteArrayCount() {
      return byteArray_.size();
    }
    /**
     * <code>repeated bytes byteArray = 1;</code>
     */
    public com.google.protobuf.ByteString getByteArray(int index) {
      return byteArray_.get(index);
    }

    private void initFields() {
      byteArray_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < byteArray_.size(); i++) {
        output.writeBytes(1, byteArray_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < byteArray_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(byteArray_.get(i));
        }
        size += dataSize;
        size += 1 * getByteArrayList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.BytesRespProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_BytesRespProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_BytesRespProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.class, com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        byteArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_BytesRespProto_descriptor;
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto build() {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto buildPartial() {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto result = new com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          byteArray_ = java.util.Collections.unmodifiableList(byteArray_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.byteArray_ = byteArray_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto) {
          return mergeFrom((com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto other) {
        if (other == com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto.getDefaultInstance()) return this;
        if (!other.byteArray_.isEmpty()) {
          if (byteArray_.isEmpty()) {
            byteArray_ = other.byteArray_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureByteArrayIsMutable();
            byteArray_.addAll(other.byteArray_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.BytesRespProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes byteArray = 1;
      private java.util.List<com.google.protobuf.ByteString> byteArray_ = java.util.Collections.emptyList();
      private void ensureByteArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          byteArray_ = new java.util.ArrayList<com.google.protobuf.ByteString>(byteArray_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getByteArrayList() {
        return java.util.Collections.unmodifiableList(byteArray_);
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public int getByteArrayCount() {
        return byteArray_.size();
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public com.google.protobuf.ByteString getByteArray(int index) {
        return byteArray_.get(index);
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public Builder setByteArray(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteArrayIsMutable();
        byteArray_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public Builder addByteArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteArrayIsMutable();
        byteArray_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public Builder addAllByteArray(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureByteArrayIsMutable();
        super.addAll(values, byteArray_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteArray = 1;</code>
       */
      public Builder clearByteArray() {
        byteArray_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.BytesRespProto)
    }

    static {
      defaultInstance = new BytesRespProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.BytesRespProto)
  }

  public interface GetRankingListRespProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.RoleRankingInfoProto rankingList = 1;
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> 
        getRankingListList();
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getRankingList(int index);
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    int getRankingListCount();
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> 
        getRankingListOrBuilderList();
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getRankingListOrBuilder(
        int index);

    // optional .proto.RoleRankingInfoProto self = 2;
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    boolean hasSelf();
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getSelf();
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getSelfOrBuilder();
  }
  /**
   * Protobuf type {@code proto.GetRankingListRespProto}
   */
  public static final class GetRankingListRespProto extends
      com.google.protobuf.GeneratedMessage
      implements GetRankingListRespProtoOrBuilder {
    // Use GetRankingListRespProto.newBuilder() to construct.
    private GetRankingListRespProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRankingListRespProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRankingListRespProto defaultInstance;
    public static GetRankingListRespProto getDefaultInstance() {
      return defaultInstance;
    }

    public GetRankingListRespProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRankingListRespProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rankingList_ = new java.util.ArrayList<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              rankingList_.add(input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = self_.toBuilder();
              }
              self_ = input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(self_);
                self_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rankingList_ = java.util.Collections.unmodifiableList(rankingList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_GetRankingListRespProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_GetRankingListRespProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.class, com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRankingListRespProto> PARSER =
        new com.google.protobuf.AbstractParser<GetRankingListRespProto>() {
      public GetRankingListRespProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRankingListRespProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRankingListRespProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .proto.RoleRankingInfoProto rankingList = 1;
    public static final int RANKINGLIST_FIELD_NUMBER = 1;
    private java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> rankingList_;
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> getRankingListList() {
      return rankingList_;
    }
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    public java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> 
        getRankingListOrBuilderList() {
      return rankingList_;
    }
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    public int getRankingListCount() {
      return rankingList_.size();
    }
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getRankingList(int index) {
      return rankingList_.get(index);
    }
    /**
     * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getRankingListOrBuilder(
        int index) {
      return rankingList_.get(index);
    }

    // optional .proto.RoleRankingInfoProto self = 2;
    public static final int SELF_FIELD_NUMBER = 2;
    private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto self_;
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    public boolean hasSelf() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getSelf() {
      return self_;
    }
    /**
     * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getSelfOrBuilder() {
      return self_;
    }

    private void initFields() {
      rankingList_ = java.util.Collections.emptyList();
      self_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rankingList_.size(); i++) {
        output.writeMessage(1, rankingList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, self_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rankingList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rankingList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, self_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GetRankingListRespProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_GetRankingListRespProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_GetRankingListRespProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.class, com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRankingListFieldBuilder();
          getSelfFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rankingListBuilder_ == null) {
          rankingList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rankingListBuilder_.clear();
        }
        if (selfBuilder_ == null) {
          self_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance();
        } else {
          selfBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.internal_static_proto_GetRankingListRespProto_descriptor;
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto build() {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto buildPartial() {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto result = new com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (rankingListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rankingList_ = java.util.Collections.unmodifiableList(rankingList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rankingList_ = rankingList_;
        } else {
          result.rankingList_ = rankingListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (selfBuilder_ == null) {
          result.self_ = self_;
        } else {
          result.self_ = selfBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto) {
          return mergeFrom((com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto other) {
        if (other == com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto.getDefaultInstance()) return this;
        if (rankingListBuilder_ == null) {
          if (!other.rankingList_.isEmpty()) {
            if (rankingList_.isEmpty()) {
              rankingList_ = other.rankingList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRankingListIsMutable();
              rankingList_.addAll(other.rankingList_);
            }
            onChanged();
          }
        } else {
          if (!other.rankingList_.isEmpty()) {
            if (rankingListBuilder_.isEmpty()) {
              rankingListBuilder_.dispose();
              rankingListBuilder_ = null;
              rankingList_ = other.rankingList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rankingListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRankingListFieldBuilder() : null;
            } else {
              rankingListBuilder_.addAllMessages(other.rankingList_);
            }
          }
        }
        if (other.hasSelf()) {
          mergeSelf(other.getSelf());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.ranking.RankingRespCmdProtoBuffer.GetRankingListRespProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.RoleRankingInfoProto rankingList = 1;
      private java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> rankingList_ =
        java.util.Collections.emptyList();
      private void ensureRankingListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rankingList_ = new java.util.ArrayList<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto>(rankingList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> rankingListBuilder_;

      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> getRankingListList() {
        if (rankingListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rankingList_);
        } else {
          return rankingListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public int getRankingListCount() {
        if (rankingListBuilder_ == null) {
          return rankingList_.size();
        } else {
          return rankingListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getRankingList(int index) {
        if (rankingListBuilder_ == null) {
          return rankingList_.get(index);
        } else {
          return rankingListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder setRankingList(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto value) {
        if (rankingListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingListIsMutable();
          rankingList_.set(index, value);
          onChanged();
        } else {
          rankingListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder setRankingList(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder builderForValue) {
        if (rankingListBuilder_ == null) {
          ensureRankingListIsMutable();
          rankingList_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankingListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder addRankingList(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto value) {
        if (rankingListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingListIsMutable();
          rankingList_.add(value);
          onChanged();
        } else {
          rankingListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder addRankingList(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto value) {
        if (rankingListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankingListIsMutable();
          rankingList_.add(index, value);
          onChanged();
        } else {
          rankingListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder addRankingList(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder builderForValue) {
        if (rankingListBuilder_ == null) {
          ensureRankingListIsMutable();
          rankingList_.add(builderForValue.build());
          onChanged();
        } else {
          rankingListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder addRankingList(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder builderForValue) {
        if (rankingListBuilder_ == null) {
          ensureRankingListIsMutable();
          rankingList_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankingListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder addAllRankingList(
          java.lang.Iterable<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto> values) {
        if (rankingListBuilder_ == null) {
          ensureRankingListIsMutable();
          super.addAll(values, rankingList_);
          onChanged();
        } else {
          rankingListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder clearRankingList() {
        if (rankingListBuilder_ == null) {
          rankingList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rankingListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public Builder removeRankingList(int index) {
        if (rankingListBuilder_ == null) {
          ensureRankingListIsMutable();
          rankingList_.remove(index);
          onChanged();
        } else {
          rankingListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder getRankingListBuilder(
          int index) {
        return getRankingListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getRankingListOrBuilder(
          int index) {
        if (rankingListBuilder_ == null) {
          return rankingList_.get(index);  } else {
          return rankingListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> 
           getRankingListOrBuilderList() {
        if (rankingListBuilder_ != null) {
          return rankingListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rankingList_);
        }
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder addRankingListBuilder() {
        return getRankingListFieldBuilder().addBuilder(
            com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder addRankingListBuilder(
          int index) {
        return getRankingListFieldBuilder().addBuilder(
            index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.RoleRankingInfoProto rankingList = 1;</code>
       */
      public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder> 
           getRankingListBuilderList() {
        return getRankingListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> 
          getRankingListFieldBuilder() {
        if (rankingListBuilder_ == null) {
          rankingListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder>(
                  rankingList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rankingList_ = null;
        }
        return rankingListBuilder_;
      }

      // optional .proto.RoleRankingInfoProto self = 2;
      private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto self_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> selfBuilder_;
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public boolean hasSelf() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto getSelf() {
        if (selfBuilder_ == null) {
          return self_;
        } else {
          return selfBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public Builder setSelf(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto value) {
        if (selfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          self_ = value;
          onChanged();
        } else {
          selfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public Builder setSelf(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder builderForValue) {
        if (selfBuilder_ == null) {
          self_ = builderForValue.build();
          onChanged();
        } else {
          selfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public Builder mergeSelf(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto value) {
        if (selfBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              self_ != com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance()) {
            self_ =
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.newBuilder(self_).mergeFrom(value).buildPartial();
          } else {
            self_ = value;
          }
          onChanged();
        } else {
          selfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public Builder clearSelf() {
        if (selfBuilder_ == null) {
          self_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.getDefaultInstance();
          onChanged();
        } else {
          selfBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder getSelfBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSelfFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder getSelfOrBuilder() {
        if (selfBuilder_ != null) {
          return selfBuilder_.getMessageOrBuilder();
        } else {
          return self_;
        }
      }
      /**
       * <code>optional .proto.RoleRankingInfoProto self = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder> 
          getSelfFieldBuilder() {
        if (selfBuilder_ == null) {
          selfBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleRankingInfoProtoOrBuilder>(
                  self_,
                  getParentForChildren(),
                  isClean());
          self_ = null;
        }
        return selfBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.GetRankingListRespProto)
    }

    static {
      defaultInstance = new GetRankingListRespProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GetRankingListRespProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BytesRespProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_BytesRespProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetRankingListRespProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GetRankingListRespProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037proto/RankingRespCmdProto.proto\022\005proto" +
      "\032\033proto/SynFightBoProto.proto\032\031proto/Glo" +
      "balBoProto.proto\"#\n\016BytesRespProto\022\021\n\tby" +
      "teArray\030\001 \003(\014\"v\n\027GetRankingListRespProto" +
      "\0220\n\013rankingList\030\001 \003(\0132\033.proto.RoleRankin" +
      "gInfoProto\022)\n\004self\030\002 \001(\0132\033.proto.RoleRan" +
      "kingInfoProtoB=\n com.funcy.g01.base.prot" +
      "o.rankingB\031RankingRespCmdProtoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_BytesRespProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_BytesRespProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_BytesRespProto_descriptor,
              new java.lang.String[] { "ByteArray", });
          internal_static_proto_GetRankingListRespProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_GetRankingListRespProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_GetRankingListRespProto_descriptor,
              new java.lang.String[] { "RankingList", "Self", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.getDescriptor(),
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
