// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/AchievementServiceRespCmdProto.proto

package com.funcy.g01.base.proto.bo.service;

public final class AchievementServiceRespProtoBuffer {
  private AchievementServiceRespProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChangeAchievementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .proto.AchievementProto achievements = 1;
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> 
        getAchievementsList();
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievements(int index);
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    int getAchievementsCount();
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> 
        getAchievementsOrBuilderList();
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ChangeAchievement}
   */
  public static final class ChangeAchievement extends
      com.google.protobuf.GeneratedMessage
      implements ChangeAchievementOrBuilder {
    // Use ChangeAchievement.newBuilder() to construct.
    private ChangeAchievement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangeAchievement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangeAchievement defaultInstance;
    public static ChangeAchievement getDefaultInstance() {
      return defaultInstance;
    }

    public ChangeAchievement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeAchievement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                achievements_ = new java.util.ArrayList<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              achievements_.add(input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          achievements_ = java.util.Collections.unmodifiableList(achievements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ChangeAchievement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ChangeAchievement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.class, com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangeAchievement> PARSER =
        new com.google.protobuf.AbstractParser<ChangeAchievement>() {
      public ChangeAchievement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeAchievement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeAchievement> getParserForType() {
      return PARSER;
    }

    // repeated .proto.AchievementProto achievements = 1;
    public static final int ACHIEVEMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> achievements_;
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> getAchievementsList() {
      return achievements_;
    }
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    public java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> 
        getAchievementsOrBuilderList() {
      return achievements_;
    }
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    public int getAchievementsCount() {
      return achievements_.size();
    }
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievements(int index) {
      return achievements_.get(index);
    }
    /**
     * <code>repeated .proto.AchievementProto achievements = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementsOrBuilder(
        int index) {
      return achievements_.get(index);
    }

    private void initFields() {
      achievements_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < achievements_.size(); i++) {
        output.writeMessage(1, achievements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < achievements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, achievements_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChangeAchievement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ChangeAchievement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ChangeAchievement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.class, com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAchievementsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (achievementsBuilder_ == null) {
          achievements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          achievementsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ChangeAchievement_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement build() {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement buildPartial() {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement result = new com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement(this);
        int from_bitField0_ = bitField0_;
        if (achievementsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            achievements_ = java.util.Collections.unmodifiableList(achievements_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.achievements_ = achievements_;
        } else {
          result.achievements_ = achievementsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement other) {
        if (other == com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement.getDefaultInstance()) return this;
        if (achievementsBuilder_ == null) {
          if (!other.achievements_.isEmpty()) {
            if (achievements_.isEmpty()) {
              achievements_ = other.achievements_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAchievementsIsMutable();
              achievements_.addAll(other.achievements_);
            }
            onChanged();
          }
        } else {
          if (!other.achievements_.isEmpty()) {
            if (achievementsBuilder_.isEmpty()) {
              achievementsBuilder_.dispose();
              achievementsBuilder_ = null;
              achievements_ = other.achievements_;
              bitField0_ = (bitField0_ & ~0x00000001);
              achievementsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAchievementsFieldBuilder() : null;
            } else {
              achievementsBuilder_.addAllMessages(other.achievements_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ChangeAchievement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .proto.AchievementProto achievements = 1;
      private java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> achievements_ =
        java.util.Collections.emptyList();
      private void ensureAchievementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          achievements_ = new java.util.ArrayList<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto>(achievements_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> achievementsBuilder_;

      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> getAchievementsList() {
        if (achievementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(achievements_);
        } else {
          return achievementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public int getAchievementsCount() {
        if (achievementsBuilder_ == null) {
          return achievements_.size();
        } else {
          return achievementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievements(int index) {
        if (achievementsBuilder_ == null) {
          return achievements_.get(index);
        } else {
          return achievementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder setAchievements(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto value) {
        if (achievementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAchievementsIsMutable();
          achievements_.set(index, value);
          onChanged();
        } else {
          achievementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder setAchievements(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder builderForValue) {
        if (achievementsBuilder_ == null) {
          ensureAchievementsIsMutable();
          achievements_.set(index, builderForValue.build());
          onChanged();
        } else {
          achievementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder addAchievements(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto value) {
        if (achievementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAchievementsIsMutable();
          achievements_.add(value);
          onChanged();
        } else {
          achievementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder addAchievements(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto value) {
        if (achievementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAchievementsIsMutable();
          achievements_.add(index, value);
          onChanged();
        } else {
          achievementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder addAchievements(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder builderForValue) {
        if (achievementsBuilder_ == null) {
          ensureAchievementsIsMutable();
          achievements_.add(builderForValue.build());
          onChanged();
        } else {
          achievementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder addAchievements(
          int index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder builderForValue) {
        if (achievementsBuilder_ == null) {
          ensureAchievementsIsMutable();
          achievements_.add(index, builderForValue.build());
          onChanged();
        } else {
          achievementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder addAllAchievements(
          java.lang.Iterable<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto> values) {
        if (achievementsBuilder_ == null) {
          ensureAchievementsIsMutable();
          super.addAll(values, achievements_);
          onChanged();
        } else {
          achievementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder clearAchievements() {
        if (achievementsBuilder_ == null) {
          achievements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          achievementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public Builder removeAchievements(int index) {
        if (achievementsBuilder_ == null) {
          ensureAchievementsIsMutable();
          achievements_.remove(index);
          onChanged();
        } else {
          achievementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder getAchievementsBuilder(
          int index) {
        return getAchievementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementsOrBuilder(
          int index) {
        if (achievementsBuilder_ == null) {
          return achievements_.get(index);  } else {
          return achievementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public java.util.List<? extends com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> 
           getAchievementsOrBuilderList() {
        if (achievementsBuilder_ != null) {
          return achievementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(achievements_);
        }
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder addAchievementsBuilder() {
        return getAchievementsFieldBuilder().addBuilder(
            com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder addAchievementsBuilder(
          int index) {
        return getAchievementsFieldBuilder().addBuilder(
            index, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.AchievementProto achievements = 1;</code>
       */
      public java.util.List<com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder> 
           getAchievementsBuilderList() {
        return getAchievementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> 
          getAchievementsFieldBuilder() {
        if (achievementsBuilder_ == null) {
          achievementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder>(
                  achievements_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          achievements_ = null;
        }
        return achievementsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.ChangeAchievement)
    }

    static {
      defaultInstance = new ChangeAchievement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ChangeAchievement)
  }

  public interface ClaimAchievementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .proto.AchievementProto achievement = 1;
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    boolean hasAchievement();
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievement();
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementOrBuilder();

    // optional bool isSuccess = 2;
    /**
     * <code>optional bool isSuccess = 2;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>optional bool isSuccess = 2;</code>
     */
    boolean getIsSuccess();
  }
  /**
   * Protobuf type {@code proto.ClaimAchievement}
   */
  public static final class ClaimAchievement extends
      com.google.protobuf.GeneratedMessage
      implements ClaimAchievementOrBuilder {
    // Use ClaimAchievement.newBuilder() to construct.
    private ClaimAchievement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClaimAchievement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClaimAchievement defaultInstance;
    public static ClaimAchievement getDefaultInstance() {
      return defaultInstance;
    }

    public ClaimAchievement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClaimAchievement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = achievement_.toBuilder();
              }
              achievement_ = input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(achievement_);
                achievement_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSuccess_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ClaimAchievement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ClaimAchievement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.class, com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.Builder.class);
    }

    public static com.google.protobuf.Parser<ClaimAchievement> PARSER =
        new com.google.protobuf.AbstractParser<ClaimAchievement>() {
      public ClaimAchievement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClaimAchievement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClaimAchievement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .proto.AchievementProto achievement = 1;
    public static final int ACHIEVEMENT_FIELD_NUMBER = 1;
    private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto achievement_;
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    public boolean hasAchievement() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievement() {
      return achievement_;
    }
    /**
     * <code>optional .proto.AchievementProto achievement = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementOrBuilder() {
      return achievement_;
    }

    // optional bool isSuccess = 2;
    public static final int ISSUCCESS_FIELD_NUMBER = 2;
    private boolean isSuccess_;
    /**
     * <code>optional bool isSuccess = 2;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isSuccess = 2;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    private void initFields() {
      achievement_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance();
      isSuccess_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, achievement_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSuccess_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, achievement_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccess_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClaimAchievement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ClaimAchievement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ClaimAchievement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.class, com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAchievementFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (achievementBuilder_ == null) {
          achievement_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance();
        } else {
          achievementBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.internal_static_proto_ClaimAchievement_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement build() {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement buildPartial() {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement result = new com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (achievementBuilder_ == null) {
          result.achievement_ = achievement_;
        } else {
          result.achievement_ = achievementBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSuccess_ = isSuccess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement other) {
        if (other == com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement.getDefaultInstance()) return this;
        if (other.hasAchievement()) {
          mergeAchievement(other.getAchievement());
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.AchievementServiceRespProtoBuffer.ClaimAchievement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .proto.AchievementProto achievement = 1;
      private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto achievement_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> achievementBuilder_;
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public boolean hasAchievement() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto getAchievement() {
        if (achievementBuilder_ == null) {
          return achievement_;
        } else {
          return achievementBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public Builder setAchievement(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto value) {
        if (achievementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          achievement_ = value;
          onChanged();
        } else {
          achievementBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public Builder setAchievement(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder builderForValue) {
        if (achievementBuilder_ == null) {
          achievement_ = builderForValue.build();
          onChanged();
        } else {
          achievementBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public Builder mergeAchievement(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto value) {
        if (achievementBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              achievement_ != com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance()) {
            achievement_ =
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.newBuilder(achievement_).mergeFrom(value).buildPartial();
          } else {
            achievement_ = value;
          }
          onChanged();
        } else {
          achievementBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public Builder clearAchievement() {
        if (achievementBuilder_ == null) {
          achievement_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.getDefaultInstance();
          onChanged();
        } else {
          achievementBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder getAchievementBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAchievementFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder getAchievementOrBuilder() {
        if (achievementBuilder_ != null) {
          return achievementBuilder_.getMessageOrBuilder();
        } else {
          return achievement_;
        }
      }
      /**
       * <code>optional .proto.AchievementProto achievement = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder> 
          getAchievementFieldBuilder() {
        if (achievementBuilder_ == null) {
          achievementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.AchievementProtoOrBuilder>(
                  achievement_,
                  getParentForChildren(),
                  isClean());
          achievement_ = null;
        }
        return achievementBuilder_;
      }

      // optional bool isSuccess = 2;
      private boolean isSuccess_ ;
      /**
       * <code>optional bool isSuccess = 2;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool isSuccess = 2;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>optional bool isSuccess = 2;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSuccess = 2;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ClaimAchievement)
    }

    static {
      defaultInstance = new ClaimAchievement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ClaimAchievement)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChangeAchievement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ChangeAchievement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ClaimAchievement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ClaimAchievement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*proto/AchievementServiceRespCmdProto.p" +
      "roto\022\005proto\032\031proto/GlobalBoProto.proto\"B" +
      "\n\021ChangeAchievement\022-\n\014achievements\030\001 \003(" +
      "\0132\027.proto.AchievementProto\"S\n\020ClaimAchie" +
      "vement\022,\n\013achievement\030\001 \001(\0132\027.proto.Achi" +
      "evementProto\022\021\n\tisSuccess\030\002 \001(\010BH\n#com.f" +
      "uncy.g01.base.proto.bo.serviceB!Achievem" +
      "entServiceRespProtoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ChangeAchievement_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ChangeAchievement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ChangeAchievement_descriptor,
              new java.lang.String[] { "Achievements", });
          internal_static_proto_ClaimAchievement_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_ClaimAchievement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ClaimAchievement_descriptor,
              new java.lang.String[] { "Achievement", "IsSuccess", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
