// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/RoleServiceReqCmdProto.proto

package com.funcy.g01.base.proto.bo.service;

public final class RoleServiceReqProtoBuffer {
  private RoleServiceReqProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SaveSoundReqProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes sounds = 1;
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getSoundsList();
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    int getSoundsCount();
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    com.google.protobuf.ByteString getSounds(int index);

    // optional int32 soundTime = 2;
    /**
     * <code>optional int32 soundTime = 2;</code>
     */
    boolean hasSoundTime();
    /**
     * <code>optional int32 soundTime = 2;</code>
     */
    int getSoundTime();
  }
  /**
   * Protobuf type {@code proto.SaveSoundReqProto}
   */
  public static final class SaveSoundReqProto extends
      com.google.protobuf.GeneratedMessage
      implements SaveSoundReqProtoOrBuilder {
    // Use SaveSoundReqProto.newBuilder() to construct.
    private SaveSoundReqProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SaveSoundReqProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SaveSoundReqProto defaultInstance;
    public static SaveSoundReqProto getDefaultInstance() {
      return defaultInstance;
    }

    public SaveSoundReqProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SaveSoundReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sounds_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              sounds_.add(input.readBytes());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              soundTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = java.util.Collections.unmodifiableList(sounds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.internal_static_proto_SaveSoundReqProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.internal_static_proto_SaveSoundReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.class, com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.Builder.class);
    }

    public static com.google.protobuf.Parser<SaveSoundReqProto> PARSER =
        new com.google.protobuf.AbstractParser<SaveSoundReqProto>() {
      public SaveSoundReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveSoundReqProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SaveSoundReqProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated bytes sounds = 1;
    public static final int SOUNDS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> sounds_;
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSoundsList() {
      return sounds_;
    }
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    public int getSoundsCount() {
      return sounds_.size();
    }
    /**
     * <code>repeated bytes sounds = 1;</code>
     */
    public com.google.protobuf.ByteString getSounds(int index) {
      return sounds_.get(index);
    }

    // optional int32 soundTime = 2;
    public static final int SOUNDTIME_FIELD_NUMBER = 2;
    private int soundTime_;
    /**
     * <code>optional int32 soundTime = 2;</code>
     */
    public boolean hasSoundTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 soundTime = 2;</code>
     */
    public int getSoundTime() {
      return soundTime_;
    }

    private void initFields() {
      sounds_ = java.util.Collections.emptyList();
      soundTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sounds_.size(); i++) {
        output.writeBytes(1, sounds_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, soundTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < sounds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(sounds_.get(i));
        }
        size += dataSize;
        size += 1 * getSoundsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, soundTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SaveSoundReqProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.internal_static_proto_SaveSoundReqProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.internal_static_proto_SaveSoundReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.class, com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sounds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        soundTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.internal_static_proto_SaveSoundReqProto_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto build() {
        com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto buildPartial() {
        com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto result = new com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = java.util.Collections.unmodifiableList(sounds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sounds_ = sounds_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.soundTime_ = soundTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto other) {
        if (other == com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto.getDefaultInstance()) return this;
        if (!other.sounds_.isEmpty()) {
          if (sounds_.isEmpty()) {
            sounds_ = other.sounds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSoundsIsMutable();
            sounds_.addAll(other.sounds_);
          }
          onChanged();
        }
        if (other.hasSoundTime()) {
          setSoundTime(other.getSoundTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.RoleServiceReqProtoBuffer.SaveSoundReqProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes sounds = 1;
      private java.util.List<com.google.protobuf.ByteString> sounds_ = java.util.Collections.emptyList();
      private void ensureSoundsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = new java.util.ArrayList<com.google.protobuf.ByteString>(sounds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSoundsList() {
        return java.util.Collections.unmodifiableList(sounds_);
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public int getSoundsCount() {
        return sounds_.size();
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public com.google.protobuf.ByteString getSounds(int index) {
        return sounds_.get(index);
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public Builder setSounds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoundsIsMutable();
        sounds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public Builder addSounds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoundsIsMutable();
        sounds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public Builder addAllSounds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSoundsIsMutable();
        super.addAll(values, sounds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 1;</code>
       */
      public Builder clearSounds() {
        sounds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // optional int32 soundTime = 2;
      private int soundTime_ ;
      /**
       * <code>optional int32 soundTime = 2;</code>
       */
      public boolean hasSoundTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 soundTime = 2;</code>
       */
      public int getSoundTime() {
        return soundTime_;
      }
      /**
       * <code>optional int32 soundTime = 2;</code>
       */
      public Builder setSoundTime(int value) {
        bitField0_ |= 0x00000002;
        soundTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 soundTime = 2;</code>
       */
      public Builder clearSoundTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        soundTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.SaveSoundReqProto)
    }

    static {
      defaultInstance = new SaveSoundReqProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.SaveSoundReqProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SaveSoundReqProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SaveSoundReqProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/RoleServiceReqCmdProto.proto\022\005pr" +
      "oto\"6\n\021SaveSoundReqProto\022\016\n\006sounds\030\001 \003(\014" +
      "\022\021\n\tsoundTime\030\002 \001(\005B@\n#com.funcy.g01.bas" +
      "e.proto.bo.serviceB\031RoleServiceReqProtoB" +
      "uffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_SaveSoundReqProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_SaveSoundReqProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_SaveSoundReqProto_descriptor,
              new java.lang.String[] { "Sounds", "SoundTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
