// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/MapServiceReqCmdProto.proto

package com.funcy.g01.base.proto.bo.service;

public final class MapServiceReqProtoBuffer {
  private MapServiceReqProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SaveMapReqProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .proto.ServerMapInfoProto params1 = 1;
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    boolean hasParams1();
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto getParams1();
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder getParams1OrBuilder();
  }
  /**
   * Protobuf type {@code proto.SaveMapReqProto}
   */
  public static final class SaveMapReqProto extends
      com.google.protobuf.GeneratedMessage
      implements SaveMapReqProtoOrBuilder {
    // Use SaveMapReqProto.newBuilder() to construct.
    private SaveMapReqProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SaveMapReqProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SaveMapReqProto defaultInstance;
    public static SaveMapReqProto getDefaultInstance() {
      return defaultInstance;
    }

    public SaveMapReqProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SaveMapReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = params1_.toBuilder();
              }
              params1_ = input.readMessage(com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params1_);
                params1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.internal_static_proto_SaveMapReqProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.internal_static_proto_SaveMapReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.class, com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.Builder.class);
    }

    public static com.google.protobuf.Parser<SaveMapReqProto> PARSER =
        new com.google.protobuf.AbstractParser<SaveMapReqProto>() {
      public SaveMapReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SaveMapReqProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SaveMapReqProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .proto.ServerMapInfoProto params1 = 1;
    public static final int PARAMS1_FIELD_NUMBER = 1;
    private com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto params1_;
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    public boolean hasParams1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto getParams1() {
      return params1_;
    }
    /**
     * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder getParams1OrBuilder() {
      return params1_;
    }

    private void initFields() {
      params1_ = com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, params1_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, params1_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SaveMapReqProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.internal_static_proto_SaveMapReqProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.internal_static_proto_SaveMapReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.class, com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParams1FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (params1Builder_ == null) {
          params1_ = com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.getDefaultInstance();
        } else {
          params1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.internal_static_proto_SaveMapReqProto_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto build() {
        com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto buildPartial() {
        com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto result = new com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (params1Builder_ == null) {
          result.params1_ = params1_;
        } else {
          result.params1_ = params1Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto other) {
        if (other == com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto.getDefaultInstance()) return this;
        if (other.hasParams1()) {
          mergeParams1(other.getParams1());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.MapServiceReqProtoBuffer.SaveMapReqProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .proto.ServerMapInfoProto params1 = 1;
      private com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto params1_ = com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder> params1Builder_;
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public boolean hasParams1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto getParams1() {
        if (params1Builder_ == null) {
          return params1_;
        } else {
          return params1Builder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public Builder setParams1(com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto value) {
        if (params1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params1_ = value;
          onChanged();
        } else {
          params1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public Builder setParams1(
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder builderForValue) {
        if (params1Builder_ == null) {
          params1_ = builderForValue.build();
          onChanged();
        } else {
          params1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public Builder mergeParams1(com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto value) {
        if (params1Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              params1_ != com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.getDefaultInstance()) {
            params1_ =
              com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.newBuilder(params1_).mergeFrom(value).buildPartial();
          } else {
            params1_ = value;
          }
          onChanged();
        } else {
          params1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public Builder clearParams1() {
        if (params1Builder_ == null) {
          params1_ = com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.getDefaultInstance();
          onChanged();
        } else {
          params1Builder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder getParams1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getParams1FieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder getParams1OrBuilder() {
        if (params1Builder_ != null) {
          return params1Builder_.getMessageOrBuilder();
        } else {
          return params1_;
        }
      }
      /**
       * <code>optional .proto.ServerMapInfoProto params1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder> 
          getParams1FieldBuilder() {
        if (params1Builder_ == null) {
          params1Builder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProto.Builder, com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.ServerMapInfoProtoOrBuilder>(
                  params1_,
                  getParentForChildren(),
                  isClean());
          params1_ = null;
        }
        return params1Builder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.SaveMapReqProto)
    }

    static {
      defaultInstance = new SaveMapReqProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.SaveMapReqProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SaveMapReqProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SaveMapReqProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!proto/MapServiceReqCmdProto.proto\022\005pro" +
      "to\032\033proto/SynFightBoProto.proto\"=\n\017SaveM" +
      "apReqProto\022*\n\007params1\030\001 \001(\0132\031.proto.Serv" +
      "erMapInfoProtoB?\n#com.funcy.g01.base.pro" +
      "to.bo.serviceB\030MapServiceReqProtoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_SaveMapReqProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_SaveMapReqProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_SaveMapReqProto_descriptor,
              new java.lang.String[] { "Params1", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.funcy.g01.base.proto.bo.SynFightBoProtoBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
