// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/RoleServiceRespCmdProto.proto

package com.funcy.g01.base.proto.bo.service;

public final class RoleServiceRespProtoBuffer {
  private RoleServiceRespProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetRoleSocialBaseInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .proto.RoleInfoVoProto role = 1;
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    boolean hasRole();
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto getRole();
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder getRoleOrBuilder();

    // optional .proto.RoleSocialBaseInfoProto socialInfo = 2;
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    boolean hasSocialInfo();
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto getSocialInfo();
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder getSocialInfoOrBuilder();

    // optional bool roleIsExist = 3;
    /**
     * <code>optional bool roleIsExist = 3;</code>
     */
    boolean hasRoleIsExist();
    /**
     * <code>optional bool roleIsExist = 3;</code>
     */
    boolean getRoleIsExist();
  }
  /**
   * Protobuf type {@code proto.GetRoleSocialBaseInfo}
   */
  public static final class GetRoleSocialBaseInfo extends
      com.google.protobuf.GeneratedMessage
      implements GetRoleSocialBaseInfoOrBuilder {
    // Use GetRoleSocialBaseInfo.newBuilder() to construct.
    private GetRoleSocialBaseInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRoleSocialBaseInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRoleSocialBaseInfo defaultInstance;
    public static GetRoleSocialBaseInfo getDefaultInstance() {
      return defaultInstance;
    }

    public GetRoleSocialBaseInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRoleSocialBaseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = role_.toBuilder();
              }
              role_ = input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(role_);
                role_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = socialInfo_.toBuilder();
              }
              socialInfo_ = input.readMessage(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(socialInfo_);
                socialInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roleIsExist_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSocialBaseInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSocialBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.class, com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRoleSocialBaseInfo> PARSER =
        new com.google.protobuf.AbstractParser<GetRoleSocialBaseInfo>() {
      public GetRoleSocialBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRoleSocialBaseInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRoleSocialBaseInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .proto.RoleInfoVoProto role = 1;
    public static final int ROLE_FIELD_NUMBER = 1;
    private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto role_;
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    public boolean hasRole() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto getRole() {
      return role_;
    }
    /**
     * <code>optional .proto.RoleInfoVoProto role = 1;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder getRoleOrBuilder() {
      return role_;
    }

    // optional .proto.RoleSocialBaseInfoProto socialInfo = 2;
    public static final int SOCIALINFO_FIELD_NUMBER = 2;
    private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto socialInfo_;
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    public boolean hasSocialInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto getSocialInfo() {
      return socialInfo_;
    }
    /**
     * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
     */
    public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder getSocialInfoOrBuilder() {
      return socialInfo_;
    }

    // optional bool roleIsExist = 3;
    public static final int ROLEISEXIST_FIELD_NUMBER = 3;
    private boolean roleIsExist_;
    /**
     * <code>optional bool roleIsExist = 3;</code>
     */
    public boolean hasRoleIsExist() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool roleIsExist = 3;</code>
     */
    public boolean getRoleIsExist() {
      return roleIsExist_;
    }

    private void initFields() {
      role_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.getDefaultInstance();
      socialInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.getDefaultInstance();
      roleIsExist_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, role_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, socialInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, roleIsExist_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, role_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, socialInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, roleIsExist_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GetRoleSocialBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSocialBaseInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSocialBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.class, com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRoleFieldBuilder();
          getSocialInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (roleBuilder_ == null) {
          role_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.getDefaultInstance();
        } else {
          roleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (socialInfoBuilder_ == null) {
          socialInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.getDefaultInstance();
        } else {
          socialInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        roleIsExist_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSocialBaseInfo_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo build() {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo buildPartial() {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo result = new com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (roleBuilder_ == null) {
          result.role_ = role_;
        } else {
          result.role_ = roleBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (socialInfoBuilder_ == null) {
          result.socialInfo_ = socialInfo_;
        } else {
          result.socialInfo_ = socialInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roleIsExist_ = roleIsExist_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo other) {
        if (other == com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo.getDefaultInstance()) return this;
        if (other.hasRole()) {
          mergeRole(other.getRole());
        }
        if (other.hasSocialInfo()) {
          mergeSocialInfo(other.getSocialInfo());
        }
        if (other.hasRoleIsExist()) {
          setRoleIsExist(other.getRoleIsExist());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSocialBaseInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .proto.RoleInfoVoProto role = 1;
      private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto role_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder> roleBuilder_;
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public boolean hasRole() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto getRole() {
        if (roleBuilder_ == null) {
          return role_;
        } else {
          return roleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public Builder setRole(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto value) {
        if (roleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          role_ = value;
          onChanged();
        } else {
          roleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public Builder setRole(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder builderForValue) {
        if (roleBuilder_ == null) {
          role_ = builderForValue.build();
          onChanged();
        } else {
          roleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public Builder mergeRole(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto value) {
        if (roleBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              role_ != com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.getDefaultInstance()) {
            role_ =
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.newBuilder(role_).mergeFrom(value).buildPartial();
          } else {
            role_ = value;
          }
          onChanged();
        } else {
          roleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public Builder clearRole() {
        if (roleBuilder_ == null) {
          role_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.getDefaultInstance();
          onChanged();
        } else {
          roleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder getRoleBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRoleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder getRoleOrBuilder() {
        if (roleBuilder_ != null) {
          return roleBuilder_.getMessageOrBuilder();
        } else {
          return role_;
        }
      }
      /**
       * <code>optional .proto.RoleInfoVoProto role = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder> 
          getRoleFieldBuilder() {
        if (roleBuilder_ == null) {
          roleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleInfoVoProtoOrBuilder>(
                  role_,
                  getParentForChildren(),
                  isClean());
          role_ = null;
        }
        return roleBuilder_;
      }

      // optional .proto.RoleSocialBaseInfoProto socialInfo = 2;
      private com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto socialInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder> socialInfoBuilder_;
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public boolean hasSocialInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto getSocialInfo() {
        if (socialInfoBuilder_ == null) {
          return socialInfo_;
        } else {
          return socialInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public Builder setSocialInfo(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto value) {
        if (socialInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          socialInfo_ = value;
          onChanged();
        } else {
          socialInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public Builder setSocialInfo(
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder builderForValue) {
        if (socialInfoBuilder_ == null) {
          socialInfo_ = builderForValue.build();
          onChanged();
        } else {
          socialInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public Builder mergeSocialInfo(com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto value) {
        if (socialInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              socialInfo_ != com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.getDefaultInstance()) {
            socialInfo_ =
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.newBuilder(socialInfo_).mergeFrom(value).buildPartial();
          } else {
            socialInfo_ = value;
          }
          onChanged();
        } else {
          socialInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public Builder clearSocialInfo() {
        if (socialInfoBuilder_ == null) {
          socialInfo_ = com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.getDefaultInstance();
          onChanged();
        } else {
          socialInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder getSocialInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSocialInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      public com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder getSocialInfoOrBuilder() {
        if (socialInfoBuilder_ != null) {
          return socialInfoBuilder_.getMessageOrBuilder();
        } else {
          return socialInfo_;
        }
      }
      /**
       * <code>optional .proto.RoleSocialBaseInfoProto socialInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder> 
          getSocialInfoFieldBuilder() {
        if (socialInfoBuilder_ == null) {
          socialInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProto.Builder, com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.RoleSocialBaseInfoProtoOrBuilder>(
                  socialInfo_,
                  getParentForChildren(),
                  isClean());
          socialInfo_ = null;
        }
        return socialInfoBuilder_;
      }

      // optional bool roleIsExist = 3;
      private boolean roleIsExist_ ;
      /**
       * <code>optional bool roleIsExist = 3;</code>
       */
      public boolean hasRoleIsExist() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool roleIsExist = 3;</code>
       */
      public boolean getRoleIsExist() {
        return roleIsExist_;
      }
      /**
       * <code>optional bool roleIsExist = 3;</code>
       */
      public Builder setRoleIsExist(boolean value) {
        bitField0_ |= 0x00000004;
        roleIsExist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool roleIsExist = 3;</code>
       */
      public Builder clearRoleIsExist() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleIsExist_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.GetRoleSocialBaseInfo)
    }

    static {
      defaultInstance = new GetRoleSocialBaseInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GetRoleSocialBaseInfo)
  }

  public interface GetRoleSoundsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes sounds = 5;
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getSoundsList();
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    int getSoundsCount();
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    com.google.protobuf.ByteString getSounds(int index);
  }
  /**
   * Protobuf type {@code proto.GetRoleSounds}
   */
  public static final class GetRoleSounds extends
      com.google.protobuf.GeneratedMessage
      implements GetRoleSoundsOrBuilder {
    // Use GetRoleSounds.newBuilder() to construct.
    private GetRoleSounds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetRoleSounds(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetRoleSounds defaultInstance;
    public static GetRoleSounds getDefaultInstance() {
      return defaultInstance;
    }

    public GetRoleSounds getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetRoleSounds(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sounds_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              sounds_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = java.util.Collections.unmodifiableList(sounds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSounds_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSounds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.class, com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.Builder.class);
    }

    public static com.google.protobuf.Parser<GetRoleSounds> PARSER =
        new com.google.protobuf.AbstractParser<GetRoleSounds>() {
      public GetRoleSounds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetRoleSounds(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetRoleSounds> getParserForType() {
      return PARSER;
    }

    // repeated bytes sounds = 5;
    public static final int SOUNDS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> sounds_;
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSoundsList() {
      return sounds_;
    }
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    public int getSoundsCount() {
      return sounds_.size();
    }
    /**
     * <code>repeated bytes sounds = 5;</code>
     */
    public com.google.protobuf.ByteString getSounds(int index) {
      return sounds_.get(index);
    }

    private void initFields() {
      sounds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sounds_.size(); i++) {
        output.writeBytes(5, sounds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < sounds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(sounds_.get(i));
        }
        size += dataSize;
        size += 1 * getSoundsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GetRoleSounds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSoundsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSounds_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSounds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.class, com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.Builder.class);
      }

      // Construct using com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sounds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.internal_static_proto_GetRoleSounds_descriptor;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds getDefaultInstanceForType() {
        return com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.getDefaultInstance();
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds build() {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds buildPartial() {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds result = new com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = java.util.Collections.unmodifiableList(sounds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sounds_ = sounds_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds) {
          return mergeFrom((com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds other) {
        if (other == com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds.getDefaultInstance()) return this;
        if (!other.sounds_.isEmpty()) {
          if (sounds_.isEmpty()) {
            sounds_ = other.sounds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSoundsIsMutable();
            sounds_.addAll(other.sounds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.funcy.g01.base.proto.bo.service.RoleServiceRespProtoBuffer.GetRoleSounds) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes sounds = 5;
      private java.util.List<com.google.protobuf.ByteString> sounds_ = java.util.Collections.emptyList();
      private void ensureSoundsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sounds_ = new java.util.ArrayList<com.google.protobuf.ByteString>(sounds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getSoundsList() {
        return java.util.Collections.unmodifiableList(sounds_);
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public int getSoundsCount() {
        return sounds_.size();
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public com.google.protobuf.ByteString getSounds(int index) {
        return sounds_.get(index);
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public Builder setSounds(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoundsIsMutable();
        sounds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public Builder addSounds(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoundsIsMutable();
        sounds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public Builder addAllSounds(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureSoundsIsMutable();
        super.addAll(values, sounds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes sounds = 5;</code>
       */
      public Builder clearSounds() {
        sounds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.GetRoleSounds)
    }

    static {
      defaultInstance = new GetRoleSounds(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.GetRoleSounds)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetRoleSocialBaseInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GetRoleSocialBaseInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetRoleSounds_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_GetRoleSounds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#proto/RoleServiceRespCmdProto.proto\022\005p" +
      "roto\032\031proto/GlobalBoProto.proto\"\206\001\n\025GetR" +
      "oleSocialBaseInfo\022$\n\004role\030\001 \001(\0132\026.proto." +
      "RoleInfoVoProto\0222\n\nsocialInfo\030\002 \001(\0132\036.pr" +
      "oto.RoleSocialBaseInfoProto\022\023\n\013roleIsExi" +
      "st\030\003 \001(\010\"\037\n\rGetRoleSounds\022\016\n\006sounds\030\005 \003(" +
      "\014BA\n#com.funcy.g01.base.proto.bo.service" +
      "B\032RoleServiceRespProtoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_GetRoleSocialBaseInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_GetRoleSocialBaseInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_GetRoleSocialBaseInfo_descriptor,
              new java.lang.String[] { "Role", "SocialInfo", "RoleIsExist", });
          internal_static_proto_GetRoleSounds_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_GetRoleSounds_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_GetRoleSounds_descriptor,
              new java.lang.String[] { "Sounds", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.funcy.g01.base.proto.bo.GlobalBoProtoBuffer.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
